GET http://localhost:8080/healthz
###

POST http://localhost:8080/healthz
###

GET http://localhost:8080/app
###

GET http://localhost:8080/app/assets
###

GET http://localhost:8080/metrics
####

POST http://localhost:8080/metrics
####

GET http://localhost:8080/reset